# Lab 03 - Payment Gateway Producer Configuration

kafka:
  # Confluent Cloud connection settings
  bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
  security-protocol: SASL_SSL
  sasl-mechanism: PLAIN
  sasl-username: ${SASL_USERNAME}
  sasl-password: ${SASL_PASSWORD}
  
  # Producer settings
  producer:
    acks: all
    retries: 3
    linger-ms: 10
    batch-size: 16384
    compression-type: snappy
    max-in-flight-requests-per-connection: 5
    enable-idempotence: true

# Application settings
app:
  topics:
    payment-requests: payment_requests
  
  # Payment gateway settings
  producer:
    message-count: 10
    delay-between-messages: 100  # milliseconds

# Lab-specific settings
lab:
  name: lab-03-payment-gateway
  version: 1.0.0

# Logging configuration
logging:
  level:
    com.acme.kafka: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Spring Boot settings
spring:
  application:
    name: lab-03-payment-gateway
  
  # JSON serialization settings
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Main class for different scenarios
scenarios:
  starter: com.acme.kafka.ProducerStarter
  solution: com.acme.kafka.ProducerSolution
  gateway: com.acme.kafka.PaymentGatewayApplication