global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'kafka-payment-demo'
    environment: 'development'

# Alertmanager configuration (optional for demo)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # FastAPI Payment Producer
  - job_name: 'payment-producer'
    static_configs:
      - targets: ['producer:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    
  # Kafka Payment Consumer
  - job_name: 'payment-consumer'
    static_configs:
      - targets: ['consumer:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true

  # Node Exporter (system metrics) - Optional
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #   scrape_interval: 30s

  # Kafka JMX Exporter (if using Confluent Kafka with JMX)
  # - job_name: 'kafka-jmx'
  #   static_configs:
  #     - targets: ['kafka:9999']
  #   scrape_interval: 30s